---
apiVersion: batch/v1
kind: Job
metadata:
  name: load-generator
spec:
  template:
    spec:
      containers:
      - name: load-backend-main
        image: williamyeh/hey
        command: ["hey"]
        args: ["-z", "10m", "-c", "50", "http://backend-main:9084"]
      - name: load-backend-stream
        image: williamyeh/hey
        command: ["hey"]
        args: ["-z", "10m", "-c", "50", "http://backend-stream:9085"]
      - name: load-frontend
        image: williamyeh/hey
        command: ["hey"]
        args: ["-z", "10m", "-c", "50", "http://frontend:3000"]
      - name: load-admin-panel
        image: williamyeh/hey
        command: ["hey"]
        args: ["-z", "10m", "-c", "50", "http://admin-panel:3001"]
      restartPolicy: Never
