apiVersion: v1
kind: Service
metadata:
  name: backend-main
spec:
  selector:
    app: backend-main
  ports:
    - name: http
      port: 9084
      targetPort: 9084
    - name: grpc-web
      port: 9083
      targetPort: 9083
  type: ClusterIP
