apiVersion: v1
kind: ConfigMap
metadata:
  name: hubble-ui-nginx
  namespace: kube-system
data:
  nginx.conf: |
    server {
        listen 8081;
        server_name localhost;
        root /app;
        index index.html;
        client_max_body_size 1G;

        location /api {
            proxy_http_version 1.1;
            proxy_pass_request_headers on;
            proxy_pass http://127.0.0.1:8090;
        }
        location / {
            if ($http_user_agent ~* "kube-probe") { access_log off; }
            # double `/index.html` is required here
            try_files $uri $uri/ /index.html /index.html;
            
            # Rewrite HTML content to prepend /hubble
            sub_filter 'href="/' 'href="/hubble/';
            sub_filter 'src="/' 'src="/hubble/';
            sub_filter 'href="css/' 'href="/hubble/css/';
            sub_filter 'src="js/' 'src="/hubble/js/';
            sub_filter_once off;
        }

        # Liveness probe
        location /healthz {
            access_log off;
            add_header Content-Type text/plain;
            return 200 'ok';
        }
    }
